title: Steven Santos
logo: /images/headshot_LinkedIn.png
description: Machine Learning & Data Science Portfolio
LinkedIn <a href="https://www.linkedin.com/in/stevenjsantos/">benchmarks</a>
#show_downloads: false
theme: jekyll-theme-minimal
